# Generated by Django 3.0.4 on 2020-05-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0004_tsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('semester', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='Tsignup',
        ),
    ]
